<%@ Page   Title="Customer Information" MasterPageFile="~/Site.Master"     Language="C#" AutoEventWireup="true" CodeBehind="ECustomerInformation.aspx.cs" Inherits="SunTranFirst.ECustomerInformation" %>

<%@ Register Assembly="System.Web.DataVisualization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" Namespace="System.Web.UI.DataVisualization.Charting" TagPrefix="asp" %>
 
<asp:Content ID="CustomerInformationContentID" ContentPlaceHolderID="CustomerInformationContent" runat="server">

    <div class="jumbotron">
          
        <h6 style="font-family:Roboto; height:40px;margin-left:40%;" >   <img alt="SunTran" style="Height:140%; Width:23%;"  src="/Photos/SunTranLogo.png" /> </h6><br />
         <asp:ImageButton style = "margin-left:45%;" ID = "backarrowbtn"  OnClick ="backarrowbtn_Click"   AlternateText="Go Back" runat = "server" ImageUrl = "/Photos/Back.png"  Height="13%" Width="5%"/>
  <br />
     <asp:Label ID="salesreportlbl" runat="server"  style="font-family:Roboto;font-size:large; font-weight:bold;margin-left:38%; color: #000000;">CUSTOMER INFORMATION</asp:Label>
       <div style="margin-left:-3%;">
           <br /> 
           <%-- OnRowEditing="custinfgw_RowEditing" OnRowUpdating="custinfgw_RowUpdating" OnRowDeleting="custinfgw_RowDeleting" OnRowCancelingEdit="custinfgw_RowCEdit"--%>
        <asp:GridView  GridLines="None"  AutoGenerateEditButton="True"  style="Font-family:Roboto" ID="customerinformationgv" runat="server"  BorderStyle="None" BorderWidth="10px"   PageSize="4" Width="1100px"   RowStyle-Height="35px"    EditRowStyle-BackColor="Gray"      BackColor="White" ForeColor="Black" BorderColor="#CCCCCC"  HeaderStyle-BorderWidth="10px" HeaderStyle-Font-Bold="True"  HeaderStyle-ForeColor="White" HeaderStyle-BackColor="Black" HeaderStyle-BorderColor="Black" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="CustomerInformationDS" DataKeyNames="CUSTID">
     <%--<asp:GridView  AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"  style="Font-family:Roboto" ID="GridView1" runat="server"  BorderStyle="None" BorderWidth="10px"   PageSize="8" Width="520px"   RowStyle-Height="35px"    EditRowStyle-BackColor="Gray"      BackColor="White" ForeColor="Black" BorderColor="#CCCCCC"  HeaderStyle-BorderWidth="10px" HeaderStyle-Font-Bold="True"  HeaderStyle-ForeColor="White" HeaderStyle-BackColor="Black" HeaderStyle-BorderColor="Black" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="CUSTID" DataSourceID="CustomerInformationDS">
 --%>
  <Columns>
                <asp:BoundField DataField="FIRSTNAME" HeaderText="FIRSTNAME" SortExpression="FIRSTNAME" />
                <asp:BoundField DataField="CUSTID" HeaderText="CUSTID" SortExpression="CUSTID" ReadOnly="True" />
                <asp:BoundField DataField="STREET_ADDRESS" HeaderText="STREET_ADDRESS" SortExpression="STREET_ADDRESS" />
                <asp:BoundField DataField="CITY" HeaderText="CITY" SortExpression="CITY" />
                <asp:BoundField DataField="STATE" HeaderText="STATE" SortExpression="STATE" />
                <asp:BoundField DataField="AGE" HeaderText="AGE" SortExpression="AGE" />
            </Columns>
            
<EditRowStyle BackColor="Gray"></EditRowStyle>

<HeaderStyle BackColor="Black" BorderColor="Black"  BorderWidth="10px" Font-Bold="True" ForeColor="White"></HeaderStyle>

<RowStyle Height="35px"></RowStyle>
            
        </asp:GridView>
       
           <asp:SqlDataSource ID="CustomerInformationDS" runat="server" ConnectionString="<%$ ConnectionStrings:SunTran %>" ProviderName="<%$ ConnectionStrings:SunTran.ProviderName %>" SelectCommand="SELECT &quot;FIRSTNAME&quot;, &quot;CUSTID&quot;, &quot;STREET_ADDRESS&quot;, &quot;CITY&quot;, &quot;STATE&quot;, &quot;AGE&quot; FROM &quot;CUSTOMERS&quot;" DeleteCommand="DELETE FROM &quot;CUSTOMERS&quot; WHERE &quot;CUSTID&quot; = :CUSTID" InsertCommand="INSERT INTO &quot;CUSTOMERS&quot; (&quot;FIRSTNAME&quot;, &quot;CUSTID&quot;, &quot;STREET_ADDRESS&quot;, &quot;CITY&quot;, &quot;STATE&quot;, &quot;AGE&quot;) VALUES (:FIRSTNAME, :CUSTID, :STREET_ADDRESS, :CITY, :STATE, :AGE)" UpdateCommand="UPDATE &quot;CUSTOMERS&quot; SET &quot;FIRSTNAME&quot; = :FIRSTNAME, &quot;STREET_ADDRESS&quot; = :STREET_ADDRESS, &quot;CITY&quot; = :CITY, &quot;STATE&quot; = :STATE, &quot;AGE&quot; = :AGE WHERE &quot;CUSTID&quot; = :CUSTID">
               <DeleteParameters>
                   <asp:Parameter Name="CUSTID" Type="String" />
               </DeleteParameters>
               <InsertParameters>
                   <asp:Parameter Name="FIRSTNAME" Type="String" />
                   <asp:Parameter Name="CUSTID" Type="String" />
                   <asp:Parameter Name="STREET_ADDRESS" Type="String" />
                   <asp:Parameter Name="CITY" Type="String" />
                   <asp:Parameter Name="STATE" Type="String" />
                   <asp:Parameter Name="AGE" Type="Decimal" />
               </InsertParameters>
               <UpdateParameters>
                   <asp:Parameter Name="FIRSTNAME" Type="String" />
                   <asp:Parameter Name="STREET_ADDRESS" Type="String" />
                   <asp:Parameter Name="CITY" Type="String" />
                   <asp:Parameter Name="STATE" Type="String" />
                   <asp:Parameter Name="AGE" Type="Decimal" />
                   <asp:Parameter Name="CUSTID" Type="String" />
               </UpdateParameters>
           </asp:SqlDataSource>
        
</div>
        </div></asp:Content>